CREATE TABLE IF NOT EXISTS projects (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    priority integer NOT NULL,
    description text,
    deliverydate date NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL CHECK (name <> ''),
    done BOOLEAN,
    projectId INTEGER REFERENCES projects(id)
);

-- list al tables
\dt

-- list all data in projects table
SELECT * FROM projects;

-- INSERT TEST DATA FOR projects
INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make a web app', 1, 'Using Javascript', '2019-05-12');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make an App', 1, 'Using Dart', '2019-05-12');

INSERT INTO projects(name, priority, description, deliverydate)
    VALUES ('Make a Desktop App', 2, 'Using C++', '2019-05-12');

-- INSERT TEST DATA FOR tasks
INSERT INTO tasks(name, done, projectId)
    VALUES('download Vuejs', false, 1);

INSERT INTO tasks(name, done, projectId)
    VALUES('Create UI Web', false, 1);

INSERT INTO tasks(name, done, projectId)
    VALUES('Download Flutter', false, 2);

INSERT INTO tasks(name, done, projectId)
    VALUES('Design the UI', false, 2);

select * from tasks;

select * from tasks where projectId = 1;